// This file is auto-generated by TanStack Router.
// In a real setup, this would be generated by the TanStack Router CLI.
// For now, we'll create a manual version.

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as AuthRoute } from './routes/auth';
import { Route as AuthLoginRoute } from './routes/auth/login';
import { Route as AuthRegisterRoute } from './routes/auth/register';
import { Route as AuthenticatedRoute } from './routes/_authenticated';
import { Route as DashboardRoute } from './routes/_authenticated/dashboard';
import { Route as CasesRoute } from './routes/_authenticated/cases';
import { Route as DocumentsRoute } from './routes/_authenticated/documents';
import { Route as ResearchRoute } from './routes/_authenticated/research';
import { Route as BillingRoute } from './routes/_authenticated/billing';
import { Route as SettingsRoute } from './routes/_authenticated/settings';

// Create the route tree
AuthRoute.addChildren([AuthLoginRoute, AuthRegisterRoute]);
AuthenticatedRoute.addChildren([
  DashboardRoute,
  CasesRoute,
  DocumentsRoute,
  ResearchRoute,
  BillingRoute,
  SettingsRoute,
]);
rootRoute.addChildren([IndexRoute, AuthRoute, AuthenticatedRoute]);

export const routeTree = rootRoute;
